### ISSUE TITLE
Is this project still maintained? :)

### ISSUE THREAD

**Issue by aiwalter** [logicabrity/aeon#3]
Hi @logicabrity ,

we tried to reach out to you regarding PyPI name `aeon` via the given mail on PyPI.

Also now we opened an issue at PyPI according to PEP 541 to request the `aeon` handle: https://github.com/pypi/support/issues/2639
But if you can see this here and respond it would be convenient!

Thanks a lot!

**Comment by logicabrity** [comment]
Please delete this or remove my e-mail address.

**Comment by aiwalter** [comment]
communication has been established, so closing this issue for now
